// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://eiqiabykntujbxldsppg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVpcWlhYnlrbnR1amJ4bGRzcHBnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM0MjEwMjgsImV4cCI6MjA1ODk5NzAyOH0.3I16J3OUlxJTAHVKpBugYG0vQt1j0xPPPEvoJLTK6ac";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);